### ISSUE TITLE
Use the same icon

### ISSUE THREAD

**Issue by PanderMusubi** [Seva-coder/Finder#11]
Please, use the same icon for in F-Droid (purple red globe with phone) as launcher icon (green circle with droid head).

**Comment by Seva-coder** [comment]
Hi! it was a bug, and on recent android versions instead of normal icon (with phone) default green droid was displayed. Now it is fixed (in v1.8, already available in f-droid) and in launcher it looks as follows -
![icon](https://user-images.githubusercontent.com/21035490/66705979-37b2ea80-ed36-11e9-8c9c-5a285fd2d874.png)

**Comment by PanderMusubi** [comment]
Thanks
