### ISSUE TITLE
Crash when GPS or Wifi is requested, after command text is changed

### ISSUE THREAD

**Issue by PopeRigby** [Seva-coder/Finder#4]
# Steps to reproduce

1. Edit WiFi or GPS command text
2. Send command text from other trusted phone

# Behavior
Finder crashes

# Expected behavior
Finder gives information

# Information
- Android version: 8.1
- Finder version: 1.6

# Note
Behavior repeats even after changing command text back to default

**Comment by Seva-coder** [comment]
thanks! I will try to fix it it in nearest future

**Comment by Seva-coder** [comment]
I repeat steps that you say and nothing crashes. But, I found that if muting feature is enabled, it crashes! I think it is because of permission features in new android. Temporary fix is disable muting feature (both requests and tracking sms).
Moreover in new android notifications also not shown (all requests and answers are notified to user).
In version v1.7 I to fix both this bugs, thanks for feedback!

**Comment by PopeRigby** [comment]
No problem. Thanks for the app

**Comment by Seva-coder** [comment]
v1.7 is released, this behavior fixed (also problem with notifications on android 8 solved). At soon it will be updated on f-droid
So, you can check new version

**Comment by PopeRigby** [comment]
Thank you
